### ISSUE TITLE
Record the GUI actions into a python file

### ISSUE THREAD

**Issue by fbob** [spakin/SimpInkScr#1]
Hello,

I just discovered your extension via [inklinea](https://inkscape.org/~inklinea/).
Many thanks for developing it !

I was wondering if it is planned to do the opposite workflow in SimpInkScr: trace/record the actions made in the GUI to tangle them in a python file for later modification and execution with different parameters for example ? 

If I understand the current workflow, the way it is implemented is from the python script to the GUI.
Is this correct ?

Anyway, many thanks for this extension, IMHO it was missing in the Inkscape ecosystem in my opinion.
THANKS !

**Comment by spakin** [comment]
> I was wondering if it is planned to do the opposite workflow in SimpInkScr: trace/record the actions made in the GUI to tangle them in a python file for later modification and execution with different parameters for example ?

That would be really cool.  I'm a big fan of the record-then-modify workflow.  Unfortunately, such a thing can't be implemented in an Inkscape extension.  Extensions get called, read and/or write the canvas, then exit.  My understanding is that one would need to modify the Inkscape core to implement a recording mechanism, but I've never looked at the Inkscape core and have no idea how difficult it would be to implement something like that.

Perhaps [file a feature request](https://inkscape.org/forums/beyond/how-to-report-bugs-or-request-new-features/) with Inkscape?

> If I understand the current workflow, the way it is implemented is from the python script to the GUI.
Is this correct ?

Correct.  The extension calls into Inkscape's [inkex API](https://inkscape.gitlab.io/extensions/documentation/) to create shapes in the GUI.

> Anyway, many thanks for this extension, IMHO it was missing in the Inkscape ecosystem in my opinion.
THANKS !

I'm glad you appreciate it, and I hope you find it useful.

**Comment by spakin** [comment]
@fbob: I'm pleased to report that as of 561226df0c2140d709c139dc44005e859dd20101, Simple Inkscape Scripting provides essentially the feature you requested.

As I mentioned [above](https://github.com/spakin/SimpInkScr/issues/1#issuecomment-928870455), an Inkscape extension can't currently record or trace GUI actions.  However, I realized that it *can* save a file in any format.  The latest version of Simple Inkscape Scripting includes an output extension that saves the current file as a Python script.  From *File* → *Save a Copy…*, select `Simple Inkscape Scripting script (*.py)` from the pull-down menu at the bottom of the dialog box.  You can then edit the script externally to Inkscape then execute it with *Extensions* → *Render* → *Simple Inkscape Scripting…*.

**Comment by fbob** [comment]
Many thanks @spakin for your kind feedback and this very exiting new feature !
Congrats and many many thanks :+1:
