### ISSUE TITLE
Create new layer

### ISSUE THREAD

**Issue by weetu** [spakin/SimpInkScr#10]
Is it possible to create a new layer? If it is, I cannot figure out how to do so - at least not correctly.

The [main wiki page](https://github.com/spakin/SimpInkScr/wiki#arbitrary-svg-objects) states that *"For example, the document as a whole can be read and modified via self.svg"*. However, when I try to access `self.svg` in a script (e.g. `layer = self.svg.add(Group('New Layer Name', is_layer=True))`), I get an exception: `NameError: name 'self' is not defined`

I had limited success with this:
```
layer = inkex.Layer.new('New Layer Name')
inkex_object(layer)
```

However, I can't then figure out how to add items to it. Any objects I create appear on the default layer, and I can't find a working way to move them to the new layer. Also, the new layer appears as a child of a new, unnamed layer - not at the top level of layers.

**Comment by weetu** [comment]
I did manage to find a way to create layers and add items to them:
```
for i in range(5):
	layername = "Layer {}".format(i+1)
	layer = inkex.Layer.new(layername)
	layer.style = 'display:none' # Start out as hidden
	inkex_object(layer)

	t = inkex.TextElement(x=str(width/2), y=str(height/2))
	t.text = "Text on {}".format(layername)
	t.style = 'font-family:Candara;font-size:20pt;text-anchor:middle'
	layer.append(t)
```

However, this is not quite idiomatic for the "Simple Inkscape Scripting" way of doing things. Perhaps this could be streamlined a bit?

**Comment by spakin** [comment]
> The [main wiki page](https://github.com/spakin/SimpInkScr/wiki#arbitrary-svg-objects) states that *"For example, the document as a whole can be read and modified via self.svg"*. However, when I try to access `self.svg` in a script (e.g. `layer = self.svg.add(Group('New Layer Name', is_layer=True))`), I get an exception: `NameError: name 'self' is not defined`

Oops.  The main wiki page is incorrect.  Simple Inkscape Scripting now exposes `svg.self` through a global variable called `svg_root`.

> However, this is not quite idiomatic for the "Simple Inkscape Scripting" way of doing things. Perhaps this could be streamlined a bit?

I think I should be able to add support for layers to Simple Inkscape Scripting.  The challenge is that "generate extensions" expect to return a list of non-top-level SVG elements.  I'll see if I can subvert the generate-extension mechanism to allow layers (a top-level element) to be created.
