### ISSUE TITLE
Allow syntax color and monospaced font for the code text box

### ISSUE THREAD

**Issue by A3EKV** [spakin/SimpInkScr#11]
Hi,
Thank you very much for this amazing extension.
I have some notes about the code text box: it doesn't use a verbatim text (monospace font) which makes code reading much harder. Also, there is no syntax coloring. For an example please take a look at this extension: https://github.com/textext/textext

Thank you very much

**Comment by spakin** [comment]
It is indeed impressive how [`textext`](https://github.com/textext/textext) is able to construct a text box for code.  Essentially, it tells Inkscape not to display a dialog box, then it creates its own dialog box piece-by-piece, handling all the text coloring, menus, and other graphical elements and user interactions itself.

As nice as `textext`'s custom dialog is, that's not the sort of thing I'm eager to maintain for Simple Inkscape Scripting.  The GUI code alone for `textext` is about as long as all of Simple Inkscape Scripting *combined* (i.e., the Python→SVG extension + the SVG→Python extension), has a number of non-standard dependencies that users would need to install, and even appears to include some platform-specific code paths.  Plus, there will always be "one more feature" that the custom interface lacks but that is provided by some user's favorite code editor and which that user can't live without.

Let me suggest instead editing a Simple Inkscape Scripting Python script in your favorite IDE or syntax-highlighting text editor, saving it to a file, and using the `Python file` field in the current GUI to load it.  When you change the file you can easily re-run it in Inkscape with Alt-Q (or whatever key sequence *Extensions* → *Previous Extension* is bound to on your platform).  That's how I routinely work myself.  I use the Simple Inkscape Scripting text box only for very trivial pieces of code.
