### ISSUE TITLE
windows issue after installing

### ISSUE THREAD

**Issue by luigipacheco** [spakin/SimpInkScr#116]
Followed the steps on the installation,

After cloning into the extensions folder and running the extension from inkscape i get the following error:

Traceback (most recent call last):
  File "C:\Program Files\Inkscape\share\inkscape\extensions\SimpInkScr\simpinkscr\simple_inkscape_scripting.py", line 36, in <module>
    import lxml
ModuleNotFoundError: No module named 'lxml'

I am assuming some libraries have to get installed first

**Comment by spakin** [comment]
Thanks for reporting back on your success.  I hope the other examples now work for you, too.
