### ISSUE TITLE
Guide id and locked properties are not preserved

### ISSUE THREAD

**Issue by user202729** [spakin/SimpInkScr#122]
## Problem

Do the following:

* Open an empty canvas.
* Draw a rectangle.
* Open the plugin and execute something harmless like `print(1)`.
* Press undo in Inkscape.
* See the rectangle deleted.

However,

* Open an empty canvas.
* Create a guide.
* Open the plugin and execute something harmless like `print(1)`.
* Press undo in Inkscape.
* The guide is not deleted.
* Press undo again. Now the guide is deleted.

The problem is that, even though `print(1)` does not change anything of the canvas, Inkscape register it as a change.

This is because the method

```
    @classmethod
    def _from_inkex_object(self, iobj):
        '''Create a Simple Inkscape Scripting SimpleGuide from an inkex
        Guide object.'''
```

does not store the original `iobj`, rather, it creates a new object with a new `id`, so that Inkscape thinks that something changed.

**Comment by spakin** [comment]
Thanks for the bug report and for tracking down the source of the problem.  In a moment I'll upload a version of the code that uses the original `iobj` instead of creating a new one.
