### ISSUE TITLE
Examples for Exporting as animation

### ISSUE THREAD

**Issue by A3EKV** [spakin/SimpInkScr#13]
I look forward to see some examples that demonstrate the power of scripting to create some animations, such as SVG animations, or exporting shapes as png and using an external tool such as ImageMagick to create gif/video files

Thanks

**Comment by spakin** [comment]
Simple Inkscape Scripting currently has no support for SVG animation, but I just thought of a really nifty way to add such support, which I'll try to code up next week.  Stay tuned.
