### ISSUE TITLE
[Wiki] Improve VSCode/external editor running instructions

### ISSUE THREAD

**Issue by swebra** [spakin/SimpInkScr#137]
This is a PR for the wiki, but being submitted as an issue due to GitHub not supporting real wiki PRs. Changes are in my wiki fork (`https://github.com/swebra/SimpInkScr.wiki.git`), with the revision history [here](https://github.com/swebra/SimpInkScr/wiki/Running/_history) and the rendered wiki page section [here](https://github.com/swebra/SimpInkScr/wiki/Running#visual-studio-code).

This updates the VSCode instructions to
1. Use the default repo name in `launch.json` (`SimpInkScr` rather than `simple_inkscape_scripting`), which should be the case for anyone following the README installation instructions
2. Use Python type hinting to inform VSCode of the available Simple Inkscape Scripting functions and variables. This largely avoids the shortcomings of the previous instructions and should be largely applicable to other external editors.

If you've never managed wiki PRs like this before (I hadn't either!), see [this gist](https://gist.github.com/larrybotha/10650410).

**Comment by spakin** [comment]
Thanks for the PR and for the pointer to the instructions for merging wiki PR.  I pushed your changes to the wiki.
