### ISSUE TITLE
[Question]-- How to get the canvas size?

### ISSUE THREAD

**Issue by ajrou** [spakin/SimpInkScr#14]
Greetings
I started today to play with the examples provided in this repository, and to be honest it's mind blowing ;)
I am reading the Wiki page to learn more about the available options/shapes, etc.

I wonder how can I access the Canvas size from within the extension?

I have tried:

```
canvas_width  = self.unittouu(svg.get('width'))
canvas_height = self.unittouu(svg.attrib['height'])
```
But it doesn't work. 

* Is there a proper way to get these info inside the extension? 
* How can I access the selected objects on the canvas?

Have a nice day

**Comment by ajrou** [comment]
Sorry, I found that at the bottom of the Wiki page: https://github.com/spakin/SimpInkScr/wiki#additional-convenience-features
>The document's width and height are provided in pre-defined variables:
>Variable: `width` (type `float`)
>Variable: `height` (type `float`)

**Comment by spakin** [comment]
Simple Inkscape Scripting exposes the root of the SVG tree via the `svg_root` variable.  (See [Arbitrary SVG objects](https://github.com/spakin/SimpInkScr/wiki#arbitrary-svg-objects) in the wiki.)  Hence, you can access the list of selected objects via `svg_root.selected`.  As an example, here's some code to rotate all selected objects counter-clockwise by 14° around the page origin:
```Python
rot = inkex.Transform()
rot.add_rotate(-14)
for svg_obj in svg_root.selected.values():
    obj = inkex_object(svg_obj)
    obj.transform = rot * obj.transform
```

**Comment by ajrou** [comment]
Thanks for the reply. I have tested it with the following shapes:

![image](https://user-images.githubusercontent.com/95747911/145363328-61df7824-c80f-4b21-ba76-a2c2ecb920ff.png)

When I run that code, I get the following error message:

```

-------------------------------------------------------------------------------
simple_inkscape_scripting.py 779 <module>
SimpleInkscapeScripting().run()

base.py 131 run
self.save_raw(self.effect())

extensions.py 193 effect
for child in fragment:

simple_inkscape_scripting.py 773 generate
exec(code, sis_globals)

<string> 5 <module>


AttributeError:
'SimpleObject' object has no attribute 'transform'
```

**Comment by spakin** [comment]
I added support for the `transform` attribute right before I posted here.  If you don't want to bother downloading the latest version of the code, here's a different example you can try:
```Python
all_objs = [inkex_object(o) for o in svg_root.selected.values()]
all_objs = [o for o in all_objs if o.bounding_box() is not None]
n = len(all_objs)
if n < 2:
    sys.exit(0)
for i in range(n - 1):
    obj1 = all_objs[i]
    center1 = obj1.bounding_box().center
    for j in range(i + 1, n):
        obj2 = all_objs[j]
        center2 = obj2.bounding_box().center
        line(center1, center2, stroke='blue', stroke_width=4)
```
That should draw a blue line from the center of every object to the center of every other object.
