### ISSUE TITLE
Inkscape crashes with connector avoidance example when ungrouping the results

### ISSUE THREAD

**Issue by ajrou** [spakin/SimpInkScr#16]
I have tried the example of connector avoidance: https://github.com/spakin/SimpInkScr/wiki#connector-avoidance

```
r1 = rect((100, 0), (150, 50), fill='#fff6d5')
r2 = rect((200, 400), (250, 450), fill='#fff6d5')
connector(r1, r2, ctype='orthogonal', curve=100)
circle((225, 225), 25, fill='red', conn_avoid=True)
```
It produces the shape without issues, but when I select the result and press `Shift` `Ctrl ` `G` to ungroup it, Inkscape crashes

![crash](https://user-images.githubusercontent.com/95747911/145199429-cf708765-06ca-41d4-b387-fd4f78f8814d.png)

I am using:

```
Inkscape 1.1.1 (1:1.1+202109281949+c3084ef5ed)

    GLib version:     2.64.6
    GTK version:      3.24.20
    glibmm version:   2.64.2
    gtkmm version:    3.24.2
    libxml2 version:  2.9.10
    libxslt version:  1.1.34
    Cairo version:    1.16.0
    Pango version:    1.44.7
    HarfBuzz version: 2.6.4
    Poppler version:  0.86.1

    OS version:       Ubuntu 20.04.3 LTS
```

**Comment by spakin** [comment]
I'm unable to reproduce the crash on an almost identical system ([Inkscape 1.1.1 AppImage](https://inkscape.org/gallery/item/29256/Inkscape-3bf5ae0-x86_64.AppImage) + newer Ubuntu):
```
Inkscape 1.1.1 (3bf5ae0, 2021-09-20)

    GLib version:     2.64.6
    GTK version:      3.24.20
    glibmm version:   2.64.2
    gtkmm version:    3.24.2
    libxml2 version:  2.9.10
    libxslt version:  1.1.34
    Cairo version:    1.16.0
    Pango version:    1.44.7
    HarfBuzz version: 2.6.4
    Poppler version:  0.86.1

    OS version:       Ubuntu 21.04
```
Perhaps try the AppImage version, and if it still crashes, [submit an Inkscape bug report](https://gitlab.com/inkscape/inbox/-/issues/)?  I'd suggest uploading the generated SVG with the grouped objects so the developers (a) have your exact page layout and (b) don't have to install Simple Inkscape Scripting, which is an additional variable.
