### ISSUE TITLE
Extend SimpInkScr to create arcs

### ISSUE THREAD

**Issue by callahanp** [spakin/SimpInkScr#2]
I'm building several simulated flight instruments and will be using .svg to represent the faces of dials in an aircraft.  These include various markings distributed around an arc, as well as colored arcs of multiple lengths.

If I can do this with the current SimpInkScr, I'd like to learn how and add documentation to the .md file.  If an additional function is needed, I'd like to learn to code it to be included in the SimpInkScr library, either locally,  as part of your library.

            arc( outside_dia, inside_dia, start_angle, end_angle,color).

The second type of arc would place a rotated rectangular shape, similar to the markings on a clock face.

I want to write a second function that may be added directly to the library or given as an example:

           radial_marks(length, width, start_angle, end_angle, angle_incr, color)

The immediate goal is to produce items like this:

![image](https://user-images.githubusercontent.com/6132176/139904649-e5de7be9-5ece-4c9e-be0a-503533102751.png)

**Comment by spakin** [comment]
An arc should be fairly easy to include in Simple Inkscript Scripting.  For consistency with `ellipse` I'll give it the following template:
```
arc(center, rx, ry, ang1, ang2, closed)
```
followed by the common parameters for transforms, connection avoidance, and style.

Radial marks are too special-purpose to include in the library, but I'll see if I can concoct an example that draws them.

**Comment by spakin** [comment]
Starting at d2aec4eae1299c6b1e98f42b43bd8d0f9689f4be, Simple Inkscape Scripting provides a usable arc mechanism.  The template is similar to what I listed in https://github.com/spakin/SimpInkScr/issues/2#issuecomment-958656761 except that the final argument is now `arc_type`, which must be one of `arc`, `slice`, or `chord`, much like the options in the Inkscape GUI.

You can find a numberless speedometer in [`examples/speedometer.py`](https://github.com/spakin/SimpInkScr/blob/d2aec4eae1299c6b1e98f42b43bd8d0f9689f4be/examples/speedometer.py).  A large fraction of the code involves placing the markings around the dial.  I hope you find that example helpful.

![speedometer](https://user-images.githubusercontent.com/650041/140243126-b762ffdd-a922-477e-bc30-db39c508749a.png)
