### ISSUE TITLE
Loaded file settings affect textbox code

### ISSUE THREAD

**Issue by peterennis** [spakin/SimpInkScr#21]
Fill is carried over from loaded script into the textbox code.

Related: https://github.com/spakin/SimpInkScr/issues/20

![Screenshot 2021-12-29 154826](https://user-images.githubusercontent.com/140737/147709174-d5816c60-10c0-4bb7-87c2-18ef7394d152.png)

**Comment by spakin** [comment]
This behavior is as intended.  The idea is that one can encode a bunch of common function definitions and parameter settings in a Python file then write a few lines of code in the *Python code* box that relies on those definitions and settings.
