### ISSUE TITLE
animation.py does not show any motion

### ISSUE THREAD

**Issue by peterennis** [spakin/SimpInkScr#26]
I read the code but there are no instructions on how to actually
display the animation.
How does it work?

I saw the readme has links to docs so I will peruse that to
see what I can find and report back.

**Comment by spakin** [comment]
Unfortunately, Inkscape cannot itself display the animation.  See the [inkscape.org Animation page](https://inkscape.org/learn/animation/) for details, but the short answer is to open the SVG file in a Web browser.
