### ISSUE TITLE
updated wiki animation example

### ISSUE THREAD

**Issue by peterennis** [spakin/SimpInkScr#27]
Following your directions on how to use animation I created an update of the
web code with svg and gif.

Commit here: https://github.com/peterennis/SimpInkScr/commit/0528fa6074a170a458f977aebe4455bf3ea4c907

1. I used ScreenToGif to get a screen recording
2. Page setup was added otherwise the animation would run from corner to corner in full screen
3. Added the clear.py code to help with testing

How can I use parameters that will make a viewbox the size of the window
and mitigate screen resize issues?

**Comment by spakin** [comment]
If I understand correctly what you're asking, I believe you want
```Python
svg_root.set('width', '100%')
svg_root.set('height', '100%')
svg_root.set('viewBox', '0 0 600 600')
```
That tells SVG to make the image the full size of its containing element, in this case the window.  Setting the view box to the rectangle (0, 0)–(600, 600) says that coordinates within that rectangle will be mapped to the containing rectangle and therefore be visible in the window.

**Comment by peterennis** [comment]
Your answer got me what I wanted.
I did not need the viewbox command and the
animation would then scale with the change in
window size.

![SPAnimationW-2](https://user-images.githubusercontent.com/140737/148667718-c3f93703-e3fe-41ae-97f0-57f27b7d7c6b.gif)

**Comment by spakin** [comment]
I'm glad to hear that worked.  Can we close this issue now?

**Comment by peterennis** [comment]
Yes

Sent from Yahoo Mail on Android 
 
  On Sat, Jan 8, 2022 at 8:32 PM, Scott ***@***.***> wrote:   


I'm glad to hear that worked. Can we close this issue now?
