### ISSUE TITLE
How to rotate each selected object about its own rotation center

### ISSUE THREAD

**Issue by SignificantCell2** [spakin/SimpInkScr#28]
I am selecting multiple paths in the canvas and when I apply the rotation transform for each selection it seems that the objects are not rotating about their own rotation center.

```
objs = svg_root.selection
for obj in objs:
   obj.transform.add_rotation(30)

```

How can specify that each `obj` should its "own" rotation center for the rotation transform?

Many thanks

**Comment by spakin** [comment]
`add_rotate` takes as additional, optional parameters the *x* and *y* coordinates around which to rotate.  Try this:
```Python
objs = svg_root.selection
for obj in objs:
    oc = obj.shape_box().center
    obj.transform.add_rotate(30, oc.x, oc.y)
```

**Comment by SignificantCell2** [comment]
Thank you for your help!
It's hard to memorize the syntax. Adding syntax highlighting or autocompletion will such a very nice feature. 
What do you think about Language Service Protocol?:

*  https://microsoft.github.io/language-server-protocol/
* https://github.com/microsoft/language-server-protocol

Have a nice day :)

**Comment by SignificantCell2** [comment]
Please note that the code above doesn't work as expected (see the shapes below when they're rotated). And in addition it has some side-effects, creating empty groups as you can see below. 

I am using Inkscape 1.2-dev

![inkscape-recording](https://user-images.githubusercontent.com/67183566/149325066-e40ae1a6-6aed-4855-9817-3715d86423f0.gif)

**Comment by spakin** [comment]
> It's hard to memorize the syntax. Adding syntax highlighting or autocompletion will such a very nice feature.
> What do you think about Language Service Protocol?:

Although it would certainly be nice, integrating syntax highlighting or autocompletion into Simple Inkscape Scripting itself would be a huge amount of work.  See #11 for a related discussion.  Even writing and maintaining a Language Service Protocol for other editors would probably require more time than I'd care to devote to it.

As for the syntax being hard to memorize I guess your best bet for now would be the Simple Inkscape Scripting [Quick reference guide](https://github.com/spakin/SimpInkScr/wiki/Quick-reference).

**Comment by spakin** [comment]
> Please note that the code above doesn't work as expected (see the shapes below when they're rotated).

The shapes that rotate unexpectedly presumably have a translation transform applied to them.  The rotation is being performed relative to the un-transformed shape.  You may be able temporarily to reverse the translation when computing the center of the shape, as follows:
```Python
objs = svg_root.selection
for obj in objs:
    un_xlate = inkex.Transform()
    un_xlate.add_translate(-obj.transform.e, -obj.transform.f)
    oc = obj.shape_box(un_xlate).center
    obj.transform.add_rotate(30, oc.x, oc.y)
```

Does that work?

> And in addition it has some side-effects, creating empty groups as you can see below.

Simple Inkscape Scripting was originally written as an Inkscape "generate" extension, which has the annoying side effect of introducing additional levels of grouping.  Circa 0a88a627af1fb57fb768a2974008d7f7b1ad92fb, it was rewritten as an "effect" extension, which should behave itself better.  Please try upgrading to the latest Simple Inkscape Scripting on GitHub and seeing if the empty groups go away.

**Comment by SignificantCell2** [comment]
Hi
Thank you for your reply. The second issue with empty groups is solved by updating the extension. 

Unfortunately, I have used your proposed code to rotate the objects but still doesn't work.  The objects move everytime I press "Apply" button. 

I believe this could be replicated by:

* Create a rectangle.
* Select it and run the SimpInkScr extension and run the code above (your suggested code)
* Keep clicking the "Apply" button after the second time the object will start moving.

**Comment by spakin** [comment]
It's time to bring out the big guns.  The following variation uses [NumPy](https://numpy.org/) to invert the transformation matrix then computes the rotation on the original, un-transformed shape:
```Python
import numpy as np

objs = svg_root.selection
for obj in objs:
    # Compute the inverse transform.
    xform = obj.transform
    m = np.array(list(xform.matrix) + [[0, 0, 1]])
    m_inv = np.linalg.inv(m)
    un_xform = inkex.Transform()
    un_xform.add_matrix(m_inv[0][0], m_inv[1][0],
                        m_inv[0][1], m_inv[1][1],
                        m_inv[0][2], m_inv[1][2])

    # Apply a rotation to the un-transformed object.
    oc = obj.shape_box(un_xform).center
    obj.transform.add_rotate(30, oc.x, oc.y)
```
Did I finally get it right?

**Comment by SignificantCell2** [comment]
I confirm that the code above using numpy works perfectly! Thank you very much.

Do you think is it a good idea to include this effect in SimpInkScr itself?  I mean by adding an option to `transform` to tell it to rotate the object about it's true rotation center? (something like your code using numpy).

Best regards

**Comment by spakin** [comment]
> I confirm that the code above using numpy works perfectly! Thank you very much.

Great!  Thanks for letting me know.
 
> Do you think is it a good idea to include this effect in SimpInkScr itself? I mean by adding an option to `transform` to tell it to rotate the object about its true rotation center? (something like your code using numpy).

If it weren't for the dependency on `numpy`, I'd definitely say yes.  But I'd like to keep Simple Inkscape Scripting's list of dependencies as short as possible.  As evidenced by #8, it's not always easy for users to get Inkscape to point to a particular Python installation in which a particular non-standard package has been installed.  I'll have to think of a way to provide comparable functionality without introducing additional dependencies.

**Comment by SignificantCell2** [comment]
Hello,

Inkscape already comes pre-shiped with several python modules and definitely numpy is included. (You can see that some standard extensions are already using it, by a simple grep).

However, the PIL module is the only exception for Macs. But for sure, Pillow will be shipped with Inkscape 1.1.2 and 1.2. Please see the message of Mac version Inkscape developer here: https://chat.inkscape.org/channel/inkscape_user?msg=dGY2ekaFAAx2XtrKt

![image](https://user-images.githubusercontent.com/67183566/149526567-89b17132-3822-49d5-ab9e-671e38c3dbbd.png)

but even if numpy is not used, I guess it is to add a function the 3x3 matrix.

Thank you

**Comment by spakin** [comment]
I'm pleased to hear that Pillow's existence can be assumed.  I'm not so sure I can rely on NumPy, though; the `setup.py` you reference begins with the comment,
> This is a test framework setup.py only, not used for packaging.

I suppose I can make the `numpy` import optional with code like
```Python
try:
    import numpy
except ModuleNotFoundError:
    pass
```
That way, if a user doesn't have `numpy` installed, the only missing Simple Inkscape Scripting feature will be "rotate around a point".

**Comment by spakin** [comment]
I just committed a set of revisions that provide `translate`, `rotate`, `scale`, and `skew` methods from all shape objects.  Your original code can now be expressed as
```Python
iobjs = svg_root.selection
for iobj in iobjs:
    obj = inkex_object(iobj)
    obj.rotate(30, 'center', first=True)
```

**Comment by SignificantCell2** [comment]
Thank you very much for the update :)

**Comment by SignificantCell2** [comment]
unfortunately, this seems to work only with Inkscape 1.2-dev.

It doesn't work with Inkscape 1.1.1, the anchor point has no effect. (tested on Ubuntu 20.04.3)

**Comment by spakin** [comment]
I hate to say it, but I can't reproduce this problem with Inkscape 1.1.1 on Ubuntu 21.10:
![rotate-around](https://user-images.githubusercontent.com/650041/150035422-d019afc2-590a-44df-ae26-d28724386b1e.gif)
