### ISSUE TITLE
The dialog box cannot be resized!!

### ISSUE THREAD

**Issue by alex2345** [spakin/SimpInkScr#3]
This issue is tested on Microsoft Win10,
with the screen resolution of 1920x1080,
with Inkscape 1.1 and many 1.2-devs.

The dialog box of "Simple Inkscape Scripting" cannot be resized, 
so I cannot see the [Apply] button,
please check.

Thank you!

**Comment by spakin** [comment]
It appears that the height of the tallest tab—in this case, Help—determines the height of the dialog box.  Interestingly, I see Apply on my 1920×1080 monitor, but perhaps I have a different default font.  (I'm running Ubuntu 21.04.)  I don't see a mechanism listed on https://wiki.inkscape.org/wiki/Extensions:_INX_widgets_and_parameters for controlling the size of the dialog box.

Although I like having basic usage information on the Help tab, I suppose I can remove most of that, retaining the https://github.com/spakin/SimpInkScr/ URL for reference.  I'll have to ponder the best balance between information available directly from the extension and information available online only.  Let me know if you have any thoughts on that.
