### ISSUE TITLE
confusing animation description in wiki 

### ISSUE THREAD

**Issue by peterennis** [spakin/SimpInkScr#30]
This:
![Screenshot 2022-01-12 195908](https://user-images.githubusercontent.com/140737/149258362-7b284e04-8f04-4234-8b21-8c020ef40472.png)

75% of 3 secs = 2.25 secs for the first key time part
25% of 3 secs = 0.75 secs for the second key time part

**Comment by spakin** [comment]
I don't follow.  What exactly do you find confusing in the description?

**Comment by peterennis** [comment]
The center dot used for multiplication is not readily available on Windows
It looks like space character replacement to show whitespace.

I coped the text into VSCode and it shows this:

![Screenshot 2022-01-13 140129](https://user-images.githubusercontent.com/140737/149409283-bdc3a90a-b6e6-413a-9091-d5169437420e.png)

In python coding style (vs. mathematical notation) this is clearer and avoids UTF-8:

(In 3 * (0.75 - 0) secs = 2.25 secs)

etc.

So the confusion was more to do with writing style and platform
differences. It just took a few more brain cycles to make sense :smile:

**Comment by SignificantCell2** [comment]
The posts above are unecessarily confusing. In case you don't get the point of his question, he is referring to the symbol `·` as shown in the screenshot:

![image](https://user-images.githubusercontent.com/67183566/149437774-0e25fdb4-10bd-4b46-9504-420281a28b99.png)

**Comment by peterennis** [comment]
The screenshot is on Windows.
The center dot is not visible on my keyboard. I did not investigate how to enter it otherwise.
The display on a browser is also as in the screenshot.

Now that I understand the text, it is no longer a problem.

**Comment by spakin** [comment]
I'm glad to hear that's settled.  I'll close the issue now.
