### ISSUE TITLE
animation example not working

### ISSUE THREAD

**Issue by peterennis** [spakin/SimpInkScr#31]
Using this code from the wiki:

![Screenshot 2022-01-14 210607](https://user-images.githubusercontent.com/140737/149608454-8a73e7b7-2dcb-4e23-9862-898404fa501c.png)

Test case here: https://github.com/peterennis/SimpInkScr/commit/9dc1d5a28540f7f40da767d6902000209c59e543

I get a green box, no animation, and no feedback.

The other examples in the list are working. I commented them out
to show this issue. The intent is to run all the examples as one test
with adjusted begin times. I tried also with repeat count = 2

How would I go about debugging? Using print("here") does not provide
any useful data other than to show the interpreter has passed the
problem line.

**Comment by spakin** [comment]
> I get a green box, no animation, and no feedback.

This appears to be bug in Simple Inkscape Scripting.  Apparently, if the objects being animated are not unique, the animation is ignored.  The good news is that this shouldn't be too hard for me to fix.

> How would I go about debugging? Using print("here") does not provide any useful data other than to show the interpreter has passed the problem line.

In this case, I discovered the animation was being discarded by saving the file and examining the SVG.  Prior to that, I stuck `inkex.utils.debug` calls throughout `simple_inkscape_scripting.py` to examine the values of various important values and to see if the control flow was what I expected it to be.

Sadly, I don't know of a better way to debug a user-level script than `print`.  It doesn't always need to output a static `here` string, though.  You can output the SVG corresponding to a Simple Inkscape Scripting object with code like
```Python
print(r1.get_inkex_object().tostring().decode('utf-8'))
```
and seeing if it looks correct.

**Comment by spakin** [comment]
Fixed.  Thanks for the bug report.

**Comment by spakin** [comment]
FYI, in 08f76f1491a3dd7ba052fc9de4205807676cba25 I added an `svg` method to all objects.  This returns the object's underlying SVG code as a string.  Hence, you can now write
```Python
print(r1.svg())
```
