### ISSUE TITLE
Show an error message when there is no selected object but a layer

### ISSUE THREAD

**Issue by SignificantCell2** [spakin/SimpInkScr#33]
I am trying the recent API of SimpInkScr using Inkscape 1.2-dev:

```
objs = svg_root.selection

for obj in objs:
   obj = inkex_object(obj)
   obj.rotate(50, 'center')
```

The document is empty but I have selected the *Layer 1* from "Object > Layer and objects" as shown below

![image](https://user-images.githubusercontent.com/67183566/149654199-e4976fe4-b48f-4d75-87c1-62d0e642bcb6.png)

But I am getting this confusing error message (I believe this could happen, if the layer is accidently selected intead of an object).

Is there an easy solution to get a meaninful error message to inform the user that the selection is a layer so it couldn't be transformed?

```
-------------------------------------------------------------------------------
simple_inkscape_scripting.py 1709 <module>
SimpleInkscapeScripting().run()

base.py 147 run
self.save_raw(self.effect())

simple_inkscape_scripting.py 1705 effect
exec(code, sis_globals)

<string> 4 <module>


simple_inkscape_scripting.py 1540 inkex_object
return SimpleObject(obj, merged_xform, conn_avoid, clip_path,

simple_inkscape_scripting.py 279 __init__
_simple_top.append_obj(self)

simple_inkscape_scripting.py 187 append_obj
self._svg_attach.append(obj._inkscape_obj)

etree.pyx 825 lxml.etree._Element.append


apihelpers.pxi 1341 lxml.etree._appendChild


ValueError:
cannot append parent to itself
```

**Comment by spakin** [comment]
Interesting.  FYI, Inkscape 1.1.1 doesn't select the contents of a layer when the layer itself is selected; this is new in Inkscape 1.2-dev.

You may be surprised to learn that it's in fact perfectly valid to apply transformations to a layer.  A layer is just a group that Inkscape marks with an `inkscape:groupmode="layer"` attribute.  Layers look like ordinary groups to SVG viewers other than Inkscape.  Hence, I believe the correct approach is for Simple Inkscape Scripting simply not to attach objects created with `inkex_object` to anything but leave them where they are.

This should take just a few lines of code.  Working on that now…

**Comment by SignificantCell2** [comment]
Thank you for your reply.
Yes, I am aware of the fact that layers in Inkscape are special groups with a specific attribute (I read that in your Wiki page and somewhere else). 

Now if a layer is selected nothing happens (this is better than a mysterious error message) and my point was to inform the user that he is selecting a layer instead of its items because that's very unlikely that his/her intent is to apply the transformation on the layer itself (on the special group).

However, there is a small issue regarding the `anchor` parameter:

```
obj.rotate(50) # it doesn't show an error when the layer is selected
```

but:

```
obj.rotate(50, 'center') # fails with the error message below
```

```
-------------------------------------------------------------------------------
simple_inkscape_scripting.py 1770 <module>
SimpleInkscapeScripting().run()

base.py 147 run
self.save_raw(self.effect())

simple_inkscape_scripting.py 1766 effect
exec(code, sis_globals)

<string> 5 <module>


simple_inkscape_scripting.py 463 rotate
around = bbox.center

AttributeError:
'NoneType' object has no attribute 'center'

```

**Comment by spakin** [comment]
I'm unable to reproduce either of the above with dcf1941caefc24c483f12e466cfe361a7d9c1402.  Here's a sample image in Inkscape 1.2-dev in which I selected the layer:
![before](https://user-images.githubusercontent.com/650041/149850663-4eea8589-5de4-4f69-832b-f227b9be420c.png)

I then ran the Simple Inkscape Scripting script.
```Python
objs = svg_root.selection
for obj in objs:
   obj = inkex_object(obj)
   obj.rotate(50)
```
This correctly rotated the layer around the origin:
![after-50](https://user-images.githubusercontent.com/650041/149850736-d6c85a98-98e5-4f21-85f5-00b9bab209e7.png)

I then ran
```Python
objs = svg_root.selection
for obj in objs:
   obj = inkex_object(obj)
   obj.rotate(50, 'center')
```
and Inkscape correctly rotated the layer around its center:
![after-50-center](https://user-images.githubusercontent.com/650041/149850768-3958e565-7cd2-453e-93c6-dc67afe2fb34.png)

Do you observe different behavior from Simple Inkscape Scripting dcf1941caefc24c483f12e466cfe361a7d9c1402?

**Comment by SignificantCell2** [comment]
Hi

Sorry I forget to mention in my last post that I am referring to an empty Layer without objects (as in my first screenshot, first post).

I believe you could reproduce that error message by selecting an empty layer. (Unfortunately, the current behaviour of Inkscape 1.2 is a little bit strange, in order to select a layer you need to click two times (not double click), and I've read somewhere that they will revert that behaviour: a small demonstration that is not related to this issue is to try to remove a layer, when you click the remove button it's likely that nothing will happen even if the layer appears to be selected, you need to click again in oder to select it ).

**Comment by spakin** [comment]
> Sorry I forget to mention in my last post that I am referring to an empty Layer without objects (as in my first screenshot, first post).

Ah, I had overlooked that fact.  I can now reproduce your problem.  Reopening the issue…

**Comment by spakin** [comment]
Simple Inkscape Scripting should now be able to transform an empty layer.  Please reopen the issue if you find a case in which that's still failing.

**Comment by SignificantCell2** [comment]
I've tested the latest commit. It works perfctly.
Thank you
