### ISSUE TITLE
integrate easing functions for animation

### ISSUE THREAD

**Issue by peterennis** [spakin/SimpInkScr#37]
I found that Robert Penner's easing functions are a standard for simple animation.
A GPL v3 port to Python is found here:

https://github.com/semitable/easing-functions

Is it possible to use in SIS? I do not know enough Python yet to
deal with the integration.

e.g., I would like to extend your rectangle animation so that the boxes
bounce back and forth using one of these easing functions.

A more general question is how to integrate other Python libraries?

**Comment by spakin** [comment]
It sounds like it should be possible to use [`easing-functions`](https://github.com/semitable/easing-functions) in Simple Inkscape Scripting.  Once you've installed the package, try putting
```Python
from easing_functions import *
```
at the top of your script and using the appropriate `Ease` objects as in the example in the [`easing-functions README.md` file](https://github.com/semitable/easing-functions/blob/1532af06126495d4ca6063f1c8ffefc9033222cc/README.md).

The difficult part is that `easing-functions` appears to work with linear time but nonlinear position (or other property) while Simple Inkscape Scripting works with nonlinear time but linear position. The first two suggestions that come to mind are as follows:

1. Invoke `ease` to find the target positions and place your objects at those positions.
2. Invoke `ease` on a large number of time values (i.e., using a small increment) to compute positions then construct a value for the target object's `animate` method's `key_times` argument based on the time that most closely matches each object's position.  Or binary search for the best time associated with a given position.

In general, it should be possible to integrate any Python library by `import`ing it appropriately.  However, there's an underlying implication that you've installed these libraries where the particular Python interpreter invoked by Inkscape will find them.  As evidenced by #8, this is not always straightforward.
