### ISSUE TITLE
Procedural generation via Inkscape's command line

### ISSUE THREAD

**Issue by xazw** [spakin/SimpInkScr#4]
_Simple Inkscape Scripting_ offers a lot of amazing possibilities for procedural generation. 

Right now however, it can be a bit cumbersome to always write Python code inside SIS's dialogue box (e.g. no syntax highlighting, potential indentation errors, etc) or having to click 'Apply' each time you write code outside of Inkscape.

At the moment, [Inkscape already supports command line arguments](https://wiki.inkscape.org/wiki/Using_the_Command_Line). Is there a way that you can then generate and export/SVGs with _Simple Inkscape Scripting_ through calls to Inkscape via the command line?

**Comment by spakin** [comment]
> Right now however, it can be a bit cumbersome to always write Python code inside SIS's dialogue box (e.g. no syntax highlighting, potential indentation errors, etc) or having to click 'Apply' each time you write code outside of Inkscape.

You can write code outside of Inkscape in your favorite editor, run it from the Simple Inkscape Scripting dialog the first time, and then re-run it (say, after editing the script) with *Extensions* → *Previous Extension* (Alt-Q on my system).  That reuses the previous options—in particular the name of the script file—and doesn't require you to click Apply.

> At the moment, Inkscape already supports command line arguments. Is there a way that you can then generate and export/SVGs with Simple Inkscape Scripting through calls to Inkscape via the command line?

Unfortunately, Inkscape doesn't provide a mechanism for passing options to extensions (e.g., the name of the Simple Inkscape Scripting script to run) via the command line, which strikes me as a major shortcoming.  However, I just encountered a recent StackOverflow post that addresses this limitation: [Inkscape - Set Extension Parameters from Command Line](https://stackoverflow.com/questions/69567035/inkscape-set-extension-parameters-from-command-line).  The advice given in that article is to run the extension directly from from the command line—without even invoking Inkscape.  I tried that myself and was able to get it to work.  The trick is that you'll need to set your `PYTHONPATH` and provide an SVG input file to which you'll add objects.  Here's the basic command I ran (Linux):
```bash
env PYTHONPATH=/usr/share/inkscape/extensions:$PYTHONPATH ~/.config/inkscape/extensions/simple_inkscape_scripting/simple_inkscape_scripting.py --py-source=my-script.py --output=output.svg input.svg
```
To create `input.svg` I simply opened Inkscape and saved the empty image as `input.svg`.

**Comment by ajrou** [comment]
Inkscape still doesn't provide a clean and complete Python binding for C++ API. I believe this is on their roadmap but I suspect it to be implemented anytime soon.

This is IMHO very important to record macros, etc.
