### ISSUE TITLE
crash - TypeError: 'dict_items' object does not support item assignment

### ISSUE THREAD

**Issue by peterennis** [spakin/SimpInkScr#40]
Testing style from this example: https://github.com/spakin/SimpInkScr/wiki/Changing-defaults/ff7589deeb37ccd10a4e64b18ec106ca012cf152#styles

I got this message:

![Screenshot 2022-02-05 143841](https://user-images.githubusercontent.com/140737/152665215-9d47e5ad-28a4-4397-b174-25813b88772f.png)

After some debugging, I could see this error message:

![Screenshot 2022-02-05 143451](https://user-images.githubusercontent.com/140737/152665293-382300d1-2e99-467d-836d-071c4bd5f5c7.png)

Code example is in this commit: https://github.com/peterennis/SimpInkScr/commit/1b3ab6f34147dcee7ef7a2c6618fc3fc1f50edc6

**Comment by spakin** [comment]
Fixed.  Thanks for the bug report.
