### ISSUE TITLE
wiki demos hard to see in Github dark mode

### ISSUE THREAD

**Issue by peterennis** [spakin/SimpInkScr#41]
I tested default light and dark modes as well as enhanced light and dark modes.
The graphics shown are not good for dark mode. They would be better with a white
background. This appears to be a problem for all the graphics.

![Screenshot 2022-02-06 150222](https://user-images.githubusercontent.com/140737/152703653-7b175eb2-43de-408a-ba5e-30d5ac4fc4d1.png)

![Screenshot 2022-02-06 150609](https://user-images.githubusercontent.com/140737/152703655-2e888dd0-b1bd-4d5e-9ffb-51a476593171.png)

**Comment by spakin** [comment]
With quite some effort, I managed to modify all images on all wiki pages—74 images if my count is correct—to include a white rather than a transparent background.  Let me know if you spot any images that are still hard to read in dark mode.

**Comment by peterennis** [comment]
I checked the wiki and it now also looks good in dark mode.

Thanks!
