### ISSUE TITLE
gradients not working as advertised

### ISSUE THREAD

**Issue by peterennis** [spakin/SimpInkScr#42]
Wiki indicates to expect something like this:

![Screenshot 2022-02-07 224926](https://user-images.githubusercontent.com/140737/152927082-ffc2d150-bdb9-4ce2-a82d-c7b24bb8dca3.png)

I get this result:

![Screenshot 2022-02-07 224609](https://user-images.githubusercontent.com/140737/152927139-83c5946b-bede-4c8c-a64b-79398e2cfd8c.png)

This commit: https://github.com/peterennis/SimpInkScr/commit/7eab4586de1c00e679d8b223532b187d3d1ccdcd

**Comment by spakin** [comment]
This is a bug in Inkscape.  I reported it to the Inkscape developers on 28 November 2021: https://gitlab.com/inkscape/inkscape/-/issues/2956.  Until they fix it, try either moving the object or grouping and ungrouping it.
