### ISSUE TITLE
Reversing a path connects gaps

### ISSUE THREAD

**Issue by jamesmckownbishop** [spakin/SimpInkScr#43]
I can create a path with a gap in it like so:

`path_1 = path([Move(64, 64), Line(64, 128), Move(64, 196), Line(64, 256)])`

If I reverse such a path, it no longer has a gap:

```
path_2 = path([Move(128, 64), Line(128, 128), Move(128, 196), Line(128, 256)])
path_2.reverse()
```

How can I reverse a path but preserve the gap?

Here is a screenshot of the result of those two snippets:
![path_and_reversed_path](https://user-images.githubusercontent.com/39485648/153282705-50bcca42-cf92-481c-982c-124f25dc6936.png)

Thank you for a sweet API!

**Comment by spakin** [comment]
Simple Inkscape Scripting is merely invoking the [`reverse`](https://inkscape.gitlab.io/extensions/documentation/source/inkex.paths.html#inkex.paths.Path.reverse) method provided by Inkscape extension API, [`inkex`](https://inkscape.gitlab.io/extensions/documentation/), which implies that this is a bug in `inkex`.  I submitted a bug report to Inkscape:

https://gitlab.com/inkscape/extensions/-/issues/445

As there's nothing more I can do myself, I'm closing this issue.  Thanks for the bug report.
