### ISSUE TITLE
How to automate the creation of guides

### ISSUE THREAD

**Issue by haschdl** [spakin/SimpInkScr#45]
Thank for such great extension! I would like to automate the tedious work of creating guides. I usually create the same guides, at 10% of the size, plus 13% bottom margin and a final guide at 7% height.
Is there a function to create guides? I couldn't find in the documentation.

**Comment by spakin** [comment]
I'm glad you like Simple Inkscape Scripting.  Guides would be a great addition to the extension.  I'll implement those when I get a chance.  In the meantime, try something low-level like this:
```Python
g = inkex.elements.Guide()
g.move_to(width/2, height/2, 45)
nv = svg_root.namedview
nv.add(g)
```
The `move_to` method is the key.  It takes the *x* and *y* position for a point on the guide and an angle in degrees by which to rotate the guide.

**Comment by spakin** [comment]
Simple Inkscape Scripting now provides a `guide` function for creating guides and a `guides` list that keeps track of all of the guides in the document.  See [Guides](https://github.com/spakin/SimpInkScr/wiki/Other-features/edcd04383ab610ff8bbf747d0669ab11ca430cb1#guides) in the wiki for details.

**Comment by haschdl** [comment]
Thank you @spakin , i will learn how to use the new feature, I’m sure it will save me a lot of time!
