### ISSUE TITLE
Float object is not callable

### ISSUE THREAD

**Issue by naturalmechanics** [spakin/SimpInkScr#47]
**Running from**
Inkscape Appimage version Inkscape 1.1.2 (0a00cf5, 2022-02-04)

**Installed by**
```
cd
cd .config/inkscape/extension
git clone https://github.com/spakin/SimpInkScr.git
```

**Trying to execute script :** 
```
numArms = 11
circle  = 2 * 3.14159265359
eachArm = circle / numArms
overlap = 0.10


    
center = (width/2, height/2)
radiusMain = 40

numCircles = 5
circleRadius = 20

for a in range(0,numArms) :
    theta = a*eachArm
    
    strt = theta - eachArm / 2 - eachArm*overlap
    stop = theta + eachArm / 2 + eachArm*overlap
    gaps = numCircles - 1
    gapWidth = (stop - strt ) / gaps
    for t in range(0,numCircles) :
        
        tt = strt + t * gapWidth
        
        x_circle_inArm = int(radiusMain * cos(tt) + center[0])
        y_circle_inArm = int(radiusMain * sin(tt) + center[1])
        circle((x_circle_inArm, y_circle_inArm), circleRadius)
```

Script up to the line `circle((x_circle_inArm, y_circle_inArm), circleRadius)` works.

**Error**
Traceback (most recent call last):
  File "simple_inkscape_scripting.py", line 2103, in <module>
    SimpleInkscapeScripting().run()
  File "/tmp/.mount_InkscaLQHf7h/usr/share/inkscape/extensions/inkex/base.py", line 131, in run
    self.save_raw(self.effect())
  File "simple_inkscape_scripting.py", line 2096, in effect
    exec(code, sis_globals)
  File "<string>", line 32, in <module>
TypeError: 'float' object is not callable

**Expected behavior** 
Cirlces along a circular arc to be drawn on canvas

**To reproduce :** 

1. Install appimage of inkscape
2. Install simple inkscape scripting from github as shown above
3. Render > simple inkscape scripting
4. Paste the code in the window
5. Apply

PLEASE help

**Comment by spakin** [comment]
You're going to kick yourself when I tell you the problem. :slightly_smiling_face: 

The second line of your code,
```Python
circle  = 2 * 3.14159265359
```
replaces Simple Inkscape Scripting's `circle` function with a `float` representing 2π, which is obviously not callable.

Change your first stanza to
```Python
numArms = 11
two_pi  = 2 * 3.14159265359
eachArm = two_pi / numArms
overlap = 0.10
```
and your code should run without error.
