### ISSUE TITLE
Is it possible to use filters via the simple scrypting extension?

### ISSUE THREAD

**Issue by thebruuu** [spakin/SimpInkScr#5]
As per title
Is it possible to use filters in python code?

btw Excellent tool, thanks!!!!

**Comment by spakin** [comment]
> Is it possible to use filters in python code?

Possible, yes.  Convenient, no.  Here's an example of drawing a yellow circle with a black shadow, the programmatic equivalent of *Filters* → *Shadows and Glows* → *Drop Shadow…*:
```Python
defs = self.svg.defs
filt = defs.add(inkex.Filter())
filt.add_primitive('feFlood',
                   **{'floodOpacity': '1',
                      'floodColor': 'black',
                      'result': 'flood'})
filt.add_primitive('feComposite',
                   **{'in': 'flood',
                      'in2': 'SourceGraphic',
                      'operator': 'in',
                      'result': 'composite1'})
filt.add_primitive('feGaussianBlur',
                   **{'in': 'composite1',
                      'stdDeviation': '3',
                      'result': 'blur'})
filt.add_primitive('feOffset',
                   **{'dx': '5',
                      'dy': '5',
                      'result': 'offset'})
filt.add_primitive('feComposite',
                   **{'in': 'SourceGraphic',
                      'in2': 'offset',
                      'operator': 'over',
                      'result': 'composite2'})

circle((width/2, height/2), 100, fill='yellow', stroke='black',
       stroke_width=2, filter='url(#%s)' % filt.get_id())
```
There's some but not much opportunity for simplifying the above with Simple Inkscape Scripting support.  Filters are fundamentally a somewhat complicated mechanism.

> btw Excellent tool, thanks!!!!

I'm glad you like it!

**Comment by thebruuu** [comment]
Hello Scott

I really apreciated your reactivity :)
Please find attached a code sample that shows how to use filters 
Hope it will be usefull:
[samplePath&Filter.py.txt](https://github.com/spakin/SimpInkScr/files/7595023/samplePath.Filter.py.txt)

**Comment by spakin** [comment]
Thanks for posting that sample.  I'll soon be releasing an update to Simple Inkscape Scripting that makes use of filters slightly more convenient by letting you use Python objects instead of strings for input and output ports.  Here's how your shadow and drawing filters can then be expressed:
```Python
global filt_shadow
filt_shadow = filter_effect('shadow')
blur = filt_shadow.add('GaussianBlur', stdDeviation=5)
comp1 = filt_shadow.add('Composite',
                        operator='atop', src1='SourceGraphic', src2=blur)
filt_shadow.add('Composite',
                operator='over', src1=comp1, src2='SourceAlpha')
cm = filt_shadow.add('ColorMatrix',
                     values='1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0 ')
filt_shadow.add('Blend', mode='normal', src1=cm, src2=blur)

filt_drawing = filter_effect('drawing')
turb = filt_drawing.add('Turbulence', type='fractalNoise', numOctaves=5,
                        seed=1, baseFrequency=[0.013, 0.013])
filt_drawing.add('DisplacementMap',
                 scale=6.6, xChannelSelector='R', yChannelSelector='G',
                 src1='SourceGraphic', src2=turb)
```
Note that `result` is gone.  `src1` and `src2` replace `in` and `in2` and accept either strings (like `SourceAlpha`) or named filter-element objects (like `comp1` in the above).  Because `in` is no longer used, the mess with `**` goes away, too.

[samplePathNew.py.txt](https://github.com/spakin/SimpInkScr/files/7596663/samplePathNew.py.txt)
