### ISSUE TITLE
Saving Script Output To SVG

### ISSUE THREAD

**Issue by oomlout** [spakin/SimpInkScr#50]
Thanks for such a lovely extension I'm having a great time with it!

I'm using it to generate electronic diagrams and would like to save the generated graphic to an SVG file.

I've been exploring with trying to get the svg structure out using the svg_root global variable but haven't been able to quite crack it.

Is this possible, or planned functionality in the future?

**Comment by spakin** [comment]
I'm glad to hear you like Simple Inkscape Scripting!

In Inkscape 1.2+ one can automate saving the current image with
```Python
inkex.command.write_svg(svg_root, '/home/oomlout/myfile.svg')
```

Does that answer your question?

**Comment by oomlout** [comment]
A perfect answer! Thanks!
