### ISSUE TITLE
vscode extension

### ISSUE THREAD

**Issue by inter1965** [spakin/SimpInkScr#54]
How about a vscode extension?

**Comment by spakin** [comment]
What features might that provide beyond VS Code's existing Python extension?

**Comment by inter1965** [comment]
side by side live svg image generation like "html preview" extension
code intellisense to existed simpinkscr's api
additional syntax highlight
maybe a inkscape-svg mode?

**Comment by spakin** [comment]
Interesting.

I have no experience developing VS Code extensions so I'll leave this issue open in case someone else comes along looking for a project to tackle.

**Comment by inter1965** [comment]
Please check the [https://github.com/spakin/SimpInkScr/pull/55](pull request).

> Interesting.
> 
> I have no experience developing VS Code extensions so I'll leave this issue open in case someone else comes along looking for a project to tackle.
