### ISSUE TITLE
remove() is not defined

### ISSUE THREAD

**Issue by williamsokol** [spakin/SimpInkScr#59]
Here is my code:
`a = rect((0,0),(50,50)) `<br>`
remove(a)`

when I run this it tells me:
"NameError: name 'remove' is not defined"

I do not know if I did anything wrong or if the code if it is a bug

**Comment by spakin** [comment]
`remove` is a method on `a`.  Try
```Python
a = rect((0,0),(50,50))
a.remove()
```
