### ISSUE TITLE
How to apply effects?

### ISSUE THREAD

**Issue by thebruuu** [spakin/SimpInkScr#6]
Hello Scott

Sorry to bother you again ... last question, I swear
What about effects, I mean inkscape:path-effect?
for example construct_grid effect?

**Comment by spakin** [comment]
I wish I knew how.  I've scoured the [`inkex` documentation](https://inkscape.gitlab.io/extensions/documentation/index.html), searched the [existing extensions](https://gitlab.com/inkscape/extensions), and looked in the [Creating New Extensions Inkscape forum](https://inkscape.org/forums/extensions/) (where [I asked if LPEs are supported](https://inkscape.org/forums/extensions/api-for-live-path-effects/) but so far to no avail.  :slightly_frowning_face:

**Comment by thebruuu** [comment]
Thank You !!!!

**Comment by ajrou** [comment]
@spakin : The fast way to get response about inkscape is: chat.inkscape.org
You can ask in the dev room or can tag other developers such as `@doctormo` (Martin Owen). I am sure he will answer that.

**Comment by spakin** [comment]
@ajrou: Thanks for the pointer.
