### ISSUE TITLE
"Styles" for text

### ISSUE THREAD

**Issue by Pojio91** [spakin/SimpInkScr#62]
Hello and thank for this wonderfull extension.
I am trying to add spacing between my letters in text created by the method "text()". I can do it manually by using the "spacing between letters" inside inkscape's text tab, but I would love to automate this.

I have tried several keywords, but can't seem to find the right one.

Do you by any chance know the keyword to add spacing between letters?
Is there a way to find the documented keywords used for the method "text()"?

thanks a bunch!

**Comment by spakin** [comment]
A handy feature of Simple Inkscape Scripting is that you manually can draw an image in Inkscape then go to *File* → *Save a Copy…*, select `Simple Inkscape Scripting script (*.py)` as the file type, and provide the name of a Python file to save to.  Inspect the resulting file, and you'll see how to reproduce the current image using a Simple Inkscape Scripting script.

In the case of adding spacing between letters, you'll find you need the [`letter-spacing`](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/letter-spacing) style.  Here's an example of specifying letterspacing within a Simple Inkscape Scripting script:

```Python
x, y = width/2, height/2

text('ANYONE WHO WOULD LETTERSPACE BLACKLETTER WOULD STEAL SHEEP.',
     (x, y - 12*pt),
     font_family='Bitstream Vera Serif, Times New Roman, serif',
     font_size='12pt',
     text_anchor='middle')

text('ANYONE WHO WOULD LETTERSPACE BLACKLETTER WOULD STEAL SHEEP.',
     (x, y + 12*pt),
     font_family='Bitstream Vera Serif, Times New Roman, serif',
     font_size='12pt',
     text_anchor='middle',
     letter_spacing='1.75pt')
```

Note that hyphens in SVG attributes (e.g., in `letter-spacing`) have to be replaced with underscores in Simple Inkscape Scripting (e.g., `letter_spacing`) to make them valid Python identifiers.

**Comment by Pojio91** [comment]
Thank you so much the prompt and thorough answer!
