### ISSUE TITLE
Strange bounding box behavior with text and get_id()

### ISSUE THREAD

**Issue by andrewzwicky** [spakin/SimpInkScr#63]
```python
V_PAD = 2
H_PAD = 5
V_SPACE = 20
H_SPACE = 50

KEYWORDS = [
    "X",
    "LONGER TEXT",
    "FIRST",
]

for index, word in enumerate(KEYWORDS):
    text_obj = text(word, (H_SPACE, (V_SPACE * index) + V_SPACE))

    bbox = text_obj.bounding_box()

    x1, x2 = bbox.x
    y1, y2 = bbox.y

    r = rect((x1 - H_PAD, y1 - V_PAD), (x2 + H_PAD, y2 + V_PAD))
```

Produces:
![image](https://user-images.githubusercontent.com/5263073/203468418-38fcfed3-0beb-4028-84a9-0eceb6dcdc58.png)

--------------------------

But if I add: `text_obj._inkscape_obj.get_id()`

```python
V_PAD = 2
H_PAD = 5
V_SPACE = 20
H_SPACE = 50

KEYWORDS = [
    "X",
    "LONGER TEXT",
    "FIRST",
]

for index, word in enumerate(KEYWORDS):
    text_obj = text(word, (H_SPACE, (V_SPACE * index) + V_SPACE))

    # ! this line somehow changes what the bounding_box calculation is?
    text_obj._inkscape_obj.get_id()

    bbox = text_obj.bounding_box()

    x1, x2 = bbox.x
    y1, y2 = bbox.y

    r = rect((x1 - H_PAD, y1 - V_PAD), (x2 + H_PAD, y2 + V_PAD))
```

I get my intended result of:
![image](https://user-images.githubusercontent.com/5263073/203468507-7fa0fb13-950d-4b25-89bb-968074e04a77.png)

I found this while doing print debugging.  Printing somehow caused the output to change, which I tracked to the object id being evaluated, which lead me to this solution.

**Comment by spakin** [comment]
Wow, that's a weird bug!  It took a while to track down, but I believe I now know what's going on.

Inkscape extensions lack an elegant way to acquire the bounding box of a piece of text.  The best approach I know is to spawn another copy of Inkscape with command-line options requesting the bounding box of a given object ID.  However, in the case of freshly generated text, an ID has not yet been assigned so invalid values come back from Inkscape.

According to the [documentation for `get_id`](https://inkscape.gitlab.io/extensions/documentation/source/inkex.elements._base.html#inkex.elements._base.BaseElement.get_id), the function will
> Get the id for the element, will set a new unique id if not set.

Hence, when you invoke `text_obj._inkscape_obj.get_id()`, this has a side effect of assigning an ID to the text object, and that enables Inkscape to return a valid bounding box.

I'll modify Simple Inkscape Scripting always to invoke `get_id` before launching Inkscape to query an object's bounding box.  That should take just a moment…
