### ISSUE TITLE
Save As 'Simple Inkscape Scripting Script .py' script does not include status of 'Automatic Region' check box for an Offset filter in the Filter Editor

### ISSUE THREAD

**Issue by thayeray** [spakin/SimpInkScr#65]
I have created an offset filter using the Filter General Settings with the 'Automatic Region' checkbox un-checked with custom values in the Coordinates and Dimensions fields. When applied to a text box, the filter dynamically buffers the text as described in this [Graphic Design StackExchange answer](https://graphicdesign.stackexchange.com/questions/120294/inkscape-for-cartography-fill-the-background-of-a-text). 
The resulting script from Save As 'Simple Inkscape Scripting Script.py' does not include the status of the 'Automatic Region' box in the Filter Editor. However, it includes the rest of the changes in the Offset filter's Filter General Settings. They are saved in the 'pt1' and 'pt2' parameters of the filter_effect(...) function call.
This means that the automatic region box needs to be manually unchecked upon running the script in order that these settings are applied. 
I do not see a parameter for unchecking the 'Automatic Region' setting in the filter_effect(...) code, but if I am missing something please advise!

**Comment by spakin** [comment]
I'm about to push an update to Simple Inkscape Scripting in which `filter_effect` supports an `auto_region` argument.  Set it to `False` to disable automatic regions.

Saving an image as a Simple Inkscape Scripting script will write `auto_region` to the generated Python file.
