### ISSUE TITLE
Feature request - adjust or get the center of the boundig box of an object or a group!

### ISSUE THREAD

**Issue by joealmond** [spakin/SimpInkScr#7]
Dear Scott!

Thak you for crating and letting us use this extension!
If you could add the feature mentioned in the title, transformations especialy rotation would be much simpler!
Thak you in advance!

Joe

**Comment by spakin** [comment]
It should be pretty easy to add a `bounding_box()` method to all shapes, which will return an [`inkex.transforms.BoundingBox`](https://inkscape.gitlab.io/extensions/documentation/source/inkex.transforms.html#inkex.transforms.BoundingBox) object.  From that, you can retrieve the center with the `center` or the `center_x` and `center_y` methods.  Stay tuned…

**Comment by joealmond** [comment]
That would be perfect!
Thak you in advance!
:pray:
