### ISSUE TITLE
Bug when saving svg as python

### ISSUE THREAD

**Issue by Alieff** [spakin/SimpInkScr#83]
When I tried to save my svg to python, then run the script in new document, I got following error:

![image](https://user-images.githubusercontent.com/9797980/224479104-b63be605-cb0e-4bc1-9afa-dce417ef1d1a.png)

I notice it miss '=' on parameter 'round'

When I checked the code, this line miss the '='

https://github.com/spakin/SimpInkScr/blob/master/simpinkscr/svg_to_simp_ink_script.py#L328

If you are open to PR, let me know

**Comment by spakin** [comment]
Yes, please go ahead and submit a PR.

Also, could you please post an SVG here that triggers the error when you save to Python?
