### ISSUE TITLE
Extension won't load in inkscape

### ISSUE THREAD

**Issue by darwinIcesurfer** [spakin/SimpInkScr#84]
I copied the zip file to the inkscape extensions directory.  Restarted Inkscape
(Inkscape version Inkscape 1.22 (732a01da63, 2022-12-09)
The extension is not listed in extensions
Opened Extension manager.  

- Everything is greyed out in Active Packages, 
- 10 Extension packages are listed under the Install packages tab -- but Simple Inkscape Scripts is not one of them

When 'extensions' is closed an error pops up:  <frozen :671: ImportWarning:
Dynamiclmpofter.exec_moduleO not found; falling back to load_moduleO
<frozen :671: ImportWarning:
Dynamiclmporter.exec_moduleO not found; falling back to load_moduleO

**Comment by darwinIcesurfer** [comment]
Spelling correction

**Comment by spakin** [comment]
There are two ways to install Simple Inkscape Scripting.  The first is to unzip the extension in your extensions directory.  (That's what I normally do.)  The second is to open the Extensions Manager, go to the Install Packages tab, and click on the little "open file" icon in the bottom right corner.  That will open a dialog box from which you can select the zip file.  Inkscape will then (silently) unzip the extension in your extensions directory.  In either case, you'll need to restart Inkscape for *Extensions* → *Render* → *Simple Inkscape Scripting* to become available.

I, too, receive an error message when I close the Extensions Manager dialog.  I don't know what's up with that.

**Comment by darwinIcesurfer** [comment]
Thanks for the feedback.  I had failed to unzip the file in the extensions
directory.  However, I'm still having issues.
With the file unzipped in the extensions directory, here is what I see when
I click on extensions.



[image: image.png]

When I click Manage Extensions I get "Orpha Extensions" after I unzip the
file.  I got nothing in here when the file was still zipped:

[image: image.png]

I don't see Simple Scripting in Install Packages either.
[image: image.png]

I'm a noob at inkscape.  I must be missing something fundamental.

Thanks again for your help.

Tim

**Comment by darwinIcesurfer** [comment]
(I did try the folder from the extension manager, I clicked on the
downloaded zip and the inkscape just sat there doing nothing with no error
messages)

Tim

**Comment by spakin** [comment]
> I'm a noob at inkscape.  I must be missing something fundamental.

No worries.  I _think_ what you're missing is that Inkscape's Extensions Manager is more rudimentary than you expect.  My understanding is that it manages primarily "blessed" extensions, of which very few exist (and Simple Inkscape Scripting isn't one of them). 
 The Extensions Manager seems to provide the ability to install other extensions only as an afterthought and doesn't really offer "management" of such extensions.

When I click the "open file" icon on the Extensions Manager's Install Packages tab, select `simple_inkscape_scripting.zip`, and click Open, I get no feedback.  Nothing has changed in Active Packages or Orphan Extensions or anything.  Then, when I close the Extension Manager, I get an error-message dialog box.  However, Simple Inkscape Scripting actually _has_ been installed.  When I quit and restart Inkscape, I see the extension under *Extensions* → *Render* → *Simple Inkscape Scripting*.  Do you?

> (I did try the folder from the extension manager, I clicked on the
downloaded zip and the inkscape just sat there doing nothing with no error
messages)

The Extensions Manager appears to use exclusively modal dialog boxes.  If you have an open dialog box hiding somewhere, everything else in Inkscape will sit there doing nothing.  Is it possible that's the situation in which you wound up?

**Comment by spakin** [comment]
I'm glad you finally have the extension installed.  I hope you find it useful.
