### ISSUE TITLE
Very long file names in tests

### ISSUE THREAD

**Issue by eeucalyptus** [spakin/SimpInkScr#89]
I'm using the plugin in Ubuntu 22.04 with an ext4-filesystem. The long file names in the tests sub-dir make the absolute paths exceed the 255 character limit for ext4. I can still use the plugin if I just leave out the tests dir. But having errors already when cloning the repo is not ideal. Please reduce the filenames to a reasonable length.

**Comment by spakin** [comment]
I guess I must be using shorter directory names than you, as I haven't run into this problem myself.

The source of the long names is the [`inkex.tester.ComparisonMixin`](https://inkscape-extensions-guide.readthedocs.io/en/latest/inkex-tester.html#inkex.tester.ComparisonMixin) class, which starts with the extension subdirectory and name (`simpinkscr.simple_inkscape_scripting`) and appends the complete program, hashing it only if it exceeds 127 characters.  With help from [Jonathan Neuhauser](https://inkscape.org/~joneuhauser/) and [Martin Owens](https://inkscape.org/~doctormo/), I managed to override `inkex.tester.ComparisonMixin` and force it to generate names of the form `sis_`⟨*hash*⟩`.out` (a 41-character base name).

I'll soon push out this modification to GitHub.
